export const UPDATE_RESOURCE_NAME = 'UPDATE_RESOURCE_NAME';
export const UPDATE_WEEKLY_ALLOCATION = 'UPDATE_WEEKLY_ALLOCATION';
export const ADD_WEEK = 'ADD_WEEK';
export const ADD_RESOURCE = 'ADD_RESOURCE';
